# Blend of BLE and WiFi for viewing / controlling CFX3

esphome:
  name: esp32-cfx3-ble-wifi
  name_add_mac_suffix: false
  friendly_name: "Sauntur CFX3 BLE and WiFi"
  comment: "Sauntur - Dometic CFX3 BLE/WiFi"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml

external_components:
  - source: github://andrewbackway/esphome-dometic_cfx_ble
    components: [dometic_cfx_ble]
  - source: github://andrewbackway/esphome-dometic_cfx_wifi
    components: [dometic_cfx3_wifi]  

esp32_ble_tracker:
#  scan_parameters:
#    active: true

#bluetooth_proxy:
#  active: true

api:
  encryption:
    key: !secret common_encryption_key

ota:
  platform: esphome

web_server:
  port: 80
  version: 3

# Enable logging
logger:
#  level: NONE
#  level: ERROR
  level: WARN
#  level: INFO
#  level: DEBUG
#  level: VERBOSE
#  level: VERY_VERBOSE
#dashboard_import:
#  package_import_url: ${package_import_url}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: HIGH
  manual_ip:
    static_ip: 192.168.8.91
    gateway: 192.168.8.254
    subnet: 255.255.255.0
    dns1: 192.168.8.9
    dns2: 8.8.8.8

ble_client:
  - mac_address: 24:6f:28:84:82:62
    id: cfx_ble_client
    auto_connect: true

dometic_cfx_ble:
  id: dometic_cfx_ble1
  ble_client_id: cfx_ble_client
  product_type: DZ  # or SZI, SZ

dometic_cfx3_wifi:
  host: "192.168.8.19"
  cooler_power:
    name: "wCFX Power"
    id: cfx_wifi_power
  device_name:
    name: "wCFX Device Name"
    id: cfx_wifi_device_name
  dc_voltage:
    name: "wCFX DC Voltage"
    id: cfx_wifi_dc_voltage
    icon: "mdi:flash"
  comp0_temp:
    name: "wCFX Z1 Temp (C)"
    id: cfx_wifi_z1_temp_c
    icon: "mdi:thermometer"
  comp1_temp:
    name: "wCFX Z2 Temp (C)"
    id: cfx_wifi_z2_temp_c
    icon: "mdi:thermometer"
  comp0_set_temp:
    name: "wCFX Z1 Target Temp"
    id: cfx_wifi_z1_temp_target_c
    icon: "mdi:thermometer"
  comp1_set_temp:
    name: "wCFX Z2 Target Temp"
    id: cfx_wifi_z2_temp_target_c
    icon: "mdi:thermometer"
  comp0_door_open:
    name: "wCFX Z1 Door"
    id: cfx_wifi_z1_door_open
    icon: "mdi:door"
  comp1_door_open:
    name: "wCFX Z2 Door"
    id: cfx_wifi_z2_door_open
    icon: "mdi:door"
  comp0_power:
    name: "wCFX Z1 Power"
    id: cfx_wifi_z1_power
  comp1_power:
    name: "wCFX Z2 Power"
    id: cfx_wifi_z2_power

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic
  # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic
  
  # Celsius sensors
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: dometic_cfx_ble1
    type: COMPARTMENT_0_MEASURED_TEMPERATURE
    name: "bCFX Z1 Temp (C)"
    id: cfx_ble_zone1_temp_c
    unit_of_measurement: "°C"
    icon: mdi:thermometer
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: dometic_cfx_ble1
    type: COMPARTMENT_1_MEASURED_TEMPERATURE
    name: "bCFX Z2 Temp (C)"
    id: cfx_ble_zone2_temp_c
    unit_of_measurement: "°C"
    icon: mdi:thermometer
  
  # Fahrenheit sensors (converted from Celsius)
  - platform: copy
    source_id: cfx_ble_zone1_temp_c
    name: "bCFX Z1 Temp (F)"
    unit_of_measurement: "°F"
    icon: mdi:thermometer
    filters:
      - lambda: return x * 9.0 / 5.0 + 32.0;
    accuracy_decimals: 1
  - platform: copy
    source_id: cfx_ble_zone2_temp_c
    name: "bCFX Z2 Temp (F)"
    unit_of_measurement: "°F"
    icon: mdi:thermometer
    filters:
      - lambda: return x * 9.0 / 5.0 + 32.0;
    accuracy_decimals: 1

  # Fahrenheit sensors (converted from Celsius)
  - platform: copy
    id: cfx_wifi_z1_temp_f
    source_id: cfx_wifi_z1_temp_c
    name: "wCFX Z1 Temp (F)"
    unit_of_measurement: "°F"
    icon: mdi:thermometer
    filters:
      - lambda: return x * 9.0 / 5.0 + 32.0;
    accuracy_decimals: 1
  - platform: copy
    id: cfx_wifi_z2_temp_f
    source_id: cfx_wifi_z2_temp_c
    name: "wCFX Z2 Temp (F)"
    unit_of_measurement: "°F"
    icon: mdi:thermometer
    filters:
      - lambda: return x * 9.0 / 5.0 + 32.0;
    accuracy_decimals: 1
  - platform: copy
    id: cfx_wifi_z1_temp_target_f
    source_id: cfx_wifi_z1_temp_target_c
    name: "wCFX Z1 Target Temp (F)"
    unit_of_measurement: "°F"
    icon: mdi:thermometer
    filters:
      - lambda: return x * 9.0 / 5.0 + 32.0;
    accuracy_decimals: 1
  - platform: copy
    id: cfx_wifi_z2_temp_target_f
    source_id: cfx_wifi_z2_temp_target_c
    name: "wCFX Z2 Target Temp (F)"
    unit_of_measurement: "°F"
    icon: mdi:thermometer
    filters:
      - lambda: return x * 9.0 / 5.0 + 32.0;
    accuracy_decimals: 1
  
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: dometic_cfx_ble1
    type: BATTERY_VOLTAGE_LEVEL
    name: "bCFX Battery Voltage"
    unit_of_measurement: "V"
    icon: mdi:car-battery

switch:
  - platform: gpio
    id: blue_led
    pin:
      number: GPIO2
      mode: OUTPUT
    name: "zESP32 Status LED"
    restore_mode: ALWAYS_OFF
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: dometic_cfx_ble1
    type: COOLER_POWER
    name: "bCFX Power"
    icon: mdi:power
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: dometic_cfx_ble1
    type: COMPARTMENT_0_POWER
    name: "bCFX Z1 Power"
    icon: mdi:snowflake
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: dometic_cfx_ble1
    type: COMPARTMENT_1_POWER
    name: "bCFX Z2 Power"
    icon: mdi:snowflake

number:
  # Celsius controls
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: dometic_cfx_ble1
    type: COMPARTMENT_0_SET_TEMPERATURE
    name: "bCFX Z1 Set Temp"
    id: cfx_zone1_set_temp_c
    unit_of_measurement: "°C"
    min_value: -22
    max_value: 10
    step: 1
    mode: box
    icon: mdi:thermometer-chevron-up
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: dometic_cfx_ble1
    type: COMPARTMENT_1_SET_TEMPERATURE
    name: "bCFX Z2 Set Temp"
    id: cfx_zone2_set_temp_c
    unit_of_measurement: "°C"
    min_value: -22
    max_value: 10
    step: 1
    mode: box
    icon: mdi:thermometer-chevron-up
  
  # Fahrenheit controls (template-based)
  - platform: template
    name: "bCFX Z1 Set Temp (F)"
    unit_of_measurement: "°F"
    min_value: -7.6  # -22°C in Fahrenheit
    max_value: 50    # 10°C in Fahrenheit
    step: 1
    mode: box
    icon: mdi:thermometer-chevron-up
    lambda: |-
      return id(cfx_zone1_set_temp_c).state * 9.0 / 5.0 + 32.0;
    set_action:
      - number.set:
          id: cfx_zone1_set_temp_c
          value: !lambda 'return (x - 32.0) * 5.0 / 9.0;'
  - platform: template
    name: "bCFX Z2 Set Temp (F)"
    unit_of_measurement: "°F"
    min_value: -7.6  # -22°C in Fahrenheit
    max_value: 50    # 10°C in Fahrenheit
    step: 1
    mode: box
    icon: mdi:thermometer-chevron-up
    lambda: |-
      return id(cfx_zone2_set_temp_c).state * 9.0 / 5.0 + 32.0;
    set_action:
      - number.set:
          id: cfx_zone2_set_temp_c
          value: !lambda 'return (x - 32.0) * 5.0 / 9.0;'

binary_sensor:
  - platform: status
    name: "Status"
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: dometic_cfx_ble1
    type: DOOR_ALERT
    name: "bCFX Door Alert"
    icon: mdi:alarm-light
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: dometic_cfx_ble1
    type: COMPARTMENT_0_DOOR_OPEN
    name: "bCFX Z1 Door Open"
    icon: mdi:door-open
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: dometic_cfx_ble1
    type: COMPARTMENT_1_DOOR_OPEN
    name: "bCFX Z2 Door Open"
    icon: mdi:door-open

text_sensor:
  - platform: version
    name: "Firmware Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      entity_category: diagnostic
  - platform: dometic_cfx_ble
    dometic_cfx_ble_id: dometic_cfx_ble1
    type: DEVICE_NAME
    name: "CFX Device Name"
    icon: mdi:label
